//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Text.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} vs {1}  work with {2} items into each collections:.
        /// </summary>
        public static string AboutCompare {
            get {
                return ResourceManager.GetString("AboutCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} ms..
        /// </summary>
        public static string AboutPerformance {
            get {
                return ResourceManager.GetString("AboutPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArrayList.
        /// </summary>
        public static string ArrayList {
            get {
                return ResourceManager.GetString("ArrayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Add:.
        /// </summary>
        public static string CompareToAdd {
            get {
                return ResourceManager.GetString("CompareToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Clear:.
        /// </summary>
        public static string CompareToClear {
            get {
                return ResourceManager.GetString("CompareToClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Search:.
        /// </summary>
        public static string CompareToSearch {
            get {
                return ResourceManager.GetString("CompareToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        public static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is faster than {1}..
        /// </summary>
        public static string FirstFaster {
            get {
                return ResourceManager.GetString("FirstFaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashTable.
        /// </summary>
        public static string HashTable {
            get {
                return ResourceManager.GetString("HashTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedList.
        /// </summary>
        public static string LinkedList {
            get {
                return ResourceManager.GetString("LinkedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu:
        ///[1] -- Compare ArrayList vs LinkedList
        ///[2] -- Compare Stack vs Queue
        ///[3] -- Compare HashTable vs Dictionary
        ///[Q] -- Exit.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press any key to exit on the main menu....
        /// </summary>
        public static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is equal to {1}..
        /// </summary>
        public static string ResultOfEqual {
            get {
                return ResourceManager.GetString("ResultOfEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} is faster than {0}..
        /// </summary>
        public static string SecondFaster {
            get {
                return ResourceManager.GetString("SecondFaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack.
        /// </summary>
        public static string Stack {
            get {
                return ResourceManager.GetString("Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Collections.
        /// </summary>
        public static string TitleConsole {
            get {
                return ResourceManager.GetString("TitleConsole", resourceCulture);
            }
        }
    }
}
